### ISSUE TITLE
Dark Souls Remaster

### ISSUE THREAD

**Issue by BlayZin** [lucidlemon/PraiseTheSave#2]
Hey I have been using your tool for quite some time now and I was wondering if you will update it for the new Dark Souls Remastered.

**Comment by lucidlemon** [comment]
thanks for reminding me, the problem is that I don't have the game yet haha, will do implement this however. I guess it should be ready in 1-2 days

**Comment by lucidlemon** [comment]
Fixed with this Release: https://github.com/lucidlemon/PraiseTheSave/releases/tag/1.1.0
