### ISSUE TITLE
Dark Souls Remastered: Save path seems changed.

### ISSUE THREAD

**Issue by gmgru1204** [lucidlemon/PraiseTheSave#4]
Hello. Thank you for hard works. I really like this tool since it makes my Dark Souls save data safe.
About the issue, I run the tool but it shows it can't find a ds1re save data exists.
I took a look to my documents, and I found that "NBGI\DARK SOULS REMASTERED" path do exist, but it is empty. There is another folder "FromSoftware\DARK SOULS REMASTERED" exists too, and the save data is in it.
I think maybe the patch released many days ago changed the save data path, but maybe it will be in "NBGI\DARK SOULS REMASTERED" again? Maybe it is better to search both path.

**Comment by lucidlemon** [comment]
ok this is weird. i still have it on NBGI, gonna start the game tonight to see if i can reproduce this.

**Comment by kumitom** [comment]
Hi lucidlemon.
I took a look on steamdb, about user cloud(https://steamdb.info/app/570940/ufs/):
![qq 20180607093324](https://user-images.githubusercontent.com/33191452/41073491-24340acc-6a36-11e8-860c-624e67f956f1.png)

So, maybe it decide the save path by some unknown reason?

**Comment by lucidlemon** [comment]
should be fixed now, if possible please do a quick check :) https://github.com/lucidlemon/PraiseTheSave/releases

**Comment by kumitom** [comment]
It's ok now.:)
Nice work!
