### ISSUE TITLE
Dark Souls2's save data backup come to "ds3" folder.

### ISSUE THREAD

**Issue by gmgru1204** [lucidlemon/PraiseTheSave#5]
App.config, row 29. Both dirDS2 and dirDS3 have a same value "ds3".
I think here is the problem.:)

**Comment by kumitom** [comment]
I've tried it myself. Changed settings in App.config only didn't work.
Then I changed Settings.Designer.cs, row 88 also, then it worked.

**Comment by lucidlemon** [comment]
installing dark souls 2 now to correct this in a working way :)

**Comment by lucidlemon** [comment]
should be fixed now, if possible please do a quick check :) https://github.com/lucidlemon/PraiseTheSave/releases

**Comment by kumitom** [comment]
It's ok now,too.:) Thanks!
